/*
 * generated by Xtext 2.10.0
 */
package org.j2sw.idea.lang


class DslFileType extends AbstractDslFileType {
	public static final DslFileType INSTANCE = new DslFileType()
	
	new() {
		super(DslLanguage.INSTANCE)
	}
}
