/*
 * generated by Xtext 2.10.0
 */
package org.j2sw.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.j2sw.idea.lang.DslLanguage

class DslCompletionContributor extends AbstractDslCompletionContributor {
	new() {
		this(DslLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
